---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  annotations:
    tekton.dev/pipelines.minVersion: 0.12.1
    tekton.dev/tags: rpm-build
  name: calculate-deps
  labels:
    build.appstudio.redhat.com/multi-platform-required: "true"
spec:
  description: |-
    RPM calculate deps task.
  params:
    - description: Package name being built
      name: package-name
      type: string
    - description: The platform/architecture we build for
      name: PLATFORM
      type: string
    - description: The branch name we build against/from
      name: target-branch
      type: string
    - description: Koji target to use
      name: koji-target
      type: string
      default: DEFAULT
    - description: RPM Build environment OCI image to run scripts in
      name: script-environment-image
      type: string
    - description: The Trusted Artifact URI pointing to the artifact with the rpm deps and source.
      name: dependencies-artifact
      type: string
    - name: ociStorage
      description: The OCI repository where the Trusted Artifacts are stored.
      type: string
    - description: Maximum seconds to wait for SSH credentials to appear
      name: ssh-wait-seconds
      type: string
      default: "300"
    - default: []
      description: Additional volume mounts needed for the build
      name: ADDITIONAL_VOLUME_MOUNTS
      type: array
  results:
    - name: calculation-artifact
      description: The Trusted Artifact URI pointing to the artifact with the result of the deps calculation.
      type: string
  stepTemplate:
    volumeMounts:
      - mountPath: /var/workdir
        name: workdir
  steps:
    - name: use-trusted-artifact
      image: quay.io/redhat-appstudio/build-trusted-artifacts:latest@sha256:9b180776a41d9a22a1c51539f1647c60defbbd55b44bbebdd4130e33512d8b0d
      args:
        - use
        - $(params.dependencies-artifact)=/var/workdir/source
    - name: mock-build
      image: "quay.io/redhat-appstudio/multi-platform-runner:01c7670e81d5120347cf0ad13372742489985e5f@sha256:246adeaaba600e207131d63a7f706cffdcdc37d8f600c56187123ec62823ff44"
      script: |
        #!/bin/bash
        set -ex
        if test "$(params.PLATFORM)" = localhost; then
          # do nothing (architecture not selected)
          exit 0
        fi
        mkdir -p ~/.ssh
        start_time=$(date +%s)
        timeout_seconds=$(params.ssh-wait-seconds)
        while true; do
          if [[ -e "/ssh/error" ]]; then
            #no server could be provisioned
            cat /ssh/error
            exit 1
          elif [[ -e "/ssh/otp" ]]; then
            curl --cacert /ssh/otp-ca -XPOST -d @/ssh/otp $(cat /ssh/otp-server) >~/.ssh/id_rsa
            echo "" >> ~/.ssh/id_rsa
            break
          elif [[ -e "/ssh/id_rsa" ]]; then
            cp /ssh/id_rsa ~/.ssh
            break
          fi

          now=$(date +%s)
          elapsed=$(( now - start_time ))
          if [ "$elapsed" -ge "$timeout_seconds" ]; then
            echo "Timed out (${timeout_seconds}s) waiting for /ssh/otp or /ssh/id_rsa" >&2
            exit 1
          fi
          sleep 2
        done

        arch=x86_64
        case $(params.PLATFORM) in
          *s390x) arch=s390x ;;
          *ppc64le) arch=ppc64le ;;
          *arm64) arch=aarch64 ;;
        esac

        chmod 0400 ~/.ssh/id_rsa
        export SSH_HOST=$(cat /ssh/host)
        export HOMEDIR=$(cat /ssh/user-dir)
        export SSH_ARGS="-o StrictHostKeyChecking=no"
        remote_cmd() { ssh $SSH_ARGS "$SSH_HOST" "$@" ; }
        send() { rsync -rva "$1" "$SSH_HOST:$2" ; }
        receive() { rsync -rva "$SSH_HOST:$1" "$2" ; }

        if [ "$SSH_HOST" == "localhost" ] ; then
          echo "Running at local host is not supported"
          exit 1
        fi

        workdir=/var/workdir

        remote_cmd echo "Hello from the other side!"

        # Allow mockbuilder (group mock) to read sources, and write results
        remote_cmd mkdir "$HOMEDIR/results" "$HOMEDIR/source"
        remote_cmd podman unshare setfacl -m g:135:r-x -m default:g:135:r-x "$HOMEDIR/source"
        remote_cmd podman unshare setfacl -m g:135:rwx -m default:g:135:rwx "$HOMEDIR/results"

        send "$workdir/source/" "$HOMEDIR/source"

        mock_img=$(params.script-environment-image)
        # podman pull has --retry=3 as a default, nevertheless it works only for download of blobs,
        # if manifest download fails it will not be applied
        for i in {1..5} ; do
            remote_cmd podman pull "$mock_img" && break
            sleep_time=$((i ** 2))
            echo "Retrying in $sleep_time seconds."
            sleep $sleep_time
        done

        ADDITIONAL_VOLUME_MOUNTS=()
        while [[ $# -gt 0 ]]; do
          case $1 in
          --additional-volume-mounts)
            shift
            while [[ $# -gt 0 && $1 != --* ]]; do
              ADDITIONAL_VOLUME_MOUNTS+=("$1")
              shift
            done
            ;;
          *)
            echo "unexpected argument: $1" >&2
            exit 2
            ;;
          esac
        done

        success=true
        VOLUME_MOUNTS=(
          -v "$HOMEDIR/source:/source"
          -v "$HOMEDIR/results:/results"
        )
        for mount in "${ADDITIONAL_VOLUME_MOUNTS[@]}"; do
          VOLUME_MOUNTS+=(-v "$mount")
        done

        remote_cmd podman run -u mockbuilder \
                              -e KOJI_TARGET="$(params.koji-target)" \
                              "${VOLUME_MOUNTS[@]}" \
                              --privileged --rm -ti "$mock_img" \
            mock -r fedora-rawhide-"$arch" \
                --spec /source/$(params.package-name).spec \
                --sources /source --resultdir /results \
                --calculate-build-dependencies \
        || success=false

        # display dnf logs (no matter the mock exit status), and propagate the
        # mock failure (terminates the whole script)
        remote_cmd "tar xvfO '$HOMEDIR'/results/chroot_scan.tar.gz 2>&1 | cat"
        $success

        remote_cmd podman run -v "$HOMEDIR/results:/results" \
                              --privileged --rm -ti "$mock_img" \
            mock-hermetic-repo \
            --lockfile /results/buildroot_lock.json \
            --output-repo /results/buildroot_repo

        resultdir=$workdir/results/$arch/results
        mkdir -p "$resultdir"
        # Send only repo and lockfile, ignore other artifacts
        receive "$HOMEDIR/results/buildroot_lock.json" "$resultdir/buildroot_lock.json"
        receive "$HOMEDIR/results/buildroot_repo" "$resultdir"
        cat "$resultdir/buildroot_lock.json"
      volumeMounts:
        - mountPath: /ssh
          name: ssh
          readOnly: true
    - args:
      - --additional-volume-mounts
      - $(params.ADDITIONAL_VOLUME_MOUNTS[*])
      computeResources:
        requests:
          ephemeral-storage: 5Gi
    - name: create-trusted-artifact
      image: quay.io/redhat-appstudio/build-trusted-artifacts:latest@sha256:9b180776a41d9a22a1c51539f1647c60defbbd55b44bbebdd4130e33512d8b0d
      args:
        - create
        - --store
        - $(params.ociStorage)
        - $(results.calculation-artifact.path)=/var/workdir/results
  volumes:
    - name: ssh
      secret:
        optional: false
        secretName: multi-platform-ssh-$(context.taskRun.name)
    - name: workdir
      emptyDir: {}
