---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  annotations:
    tekton.dev/pipelines.minVersion: 0.12.1
    tekton.dev/tags: rpm-build
  name: calculate-deps
  labels:
    build.appstudio.redhat.com/multi-platform-required: "true"
spec:
  description: |-
    RPM calculate deps task.
  params:
    - description: Package name being built
      name: package-name
      type: string
    - description: The platform/architecture we build for
      name: PLATFORM
      type: string
    - description: The branch name we build against/from
      name: target-branch
      type: string
    - description: Koji target to use
      name: koji-target
      type: string
      default: DEFAULT
    - description: RPM Build environment OCI image to run scripts in
      name: script-environment-image
      type: string
    - description: The Trusted Artifact URI pointing to the artifact with the rpm deps and source.
      name: dependencies-artifact
      type: string
    - name: ociStorage
      description: The OCI repository where the Trusted Artifacts are stored.
      type: string
    - name: specfile
      description: |
        Name of specfile when specfile doesn't have the same prefix name as package name.
        Default is null and package-name.spec is used.
      type: string
      default: "300"
    - default: does-not-exist
      description: Name of a secret which will be made available to the mock command
      name: ADDITIONAL_SECRET
      type: string
  results:
    - name: calculation-artifact
      description: The Trusted Artifact URI pointing to the artifact with the result of the deps calculation.
      type: string
  stepTemplate:
    volumeMounts:
      - mountPath: /var/workdir
        name: workdir
  steps:
    - name: use-trusted-artifact
      image: quay.io/redhat-appstudio/build-trusted-artifacts:latest@sha256:9b180776a41d9a22a1c51539f1647c60defbbd55b44bbebdd4130e33512d8b0d
      args:
        - use
        - $(params.dependencies-artifact)=/var/workdir/source
    - name: mock-build
      image: "quay.io/redhat-appstudio/multi-platform-runner:01c7670e81d5120347cf0ad13372742489985e5f@sha256:246adeaaba600e207131d63a7f706cffdcdc37d8f600c56187123ec62823ff44"
      script: |
        #!/bin/bash
        set -ex
        if test "$(params.PLATFORM)" = localhost; then
          # do nothing (architecture not selected)
          exit 0
        fi
        mkdir -p ~/.ssh
        if [ -e "/ssh/error" ]; then
          #no server could be provisioned
          cat /ssh/error
          exit 1
        elif [ -e "/ssh/otp" ]; then
         curl --cacert /ssh/otp-ca -XPOST -d @/ssh/otp $(cat /ssh/otp-server) >~/.ssh/id_rsa
         echo "" >> ~/.ssh/id_rsa
        else
          cp /ssh/id_rsa ~/.ssh
        fi

        arch=x86_64
        case $(params.PLATFORM) in
          *s390x) arch=s390x ;;
          *ppc64le) arch=ppc64le ;;
          *arm64) arch=aarch64 ;;
        esac

        mkdir -p /var/workdir/config
        cat <<EOF > /var/workdir/config/mock.cfg
        config_opts['target_arch'] = '$arch'
        config_opts['legal_host_arches'] = ('$arch',)

        config_opts['root'] = 'local-{{ target_arch }}'

        # NOTE: The prefetched RPMs repo doesn't include this. Should it?
        # config_opts['chroot_setup_cmd'] = 'install @buildsys-build'
        # NOTE: The buildsys repo we got from hermeto doesn't have the buildsys-build group defined. So
        # we just expand the group into individual packages here.
        config_opts['chroot_setup_cmd'] = 'install bash bzip2 coreutils cpio diffutils fedora-release-common findutils gawk glibc-minimal-langpack grep gzip info patch redhat-rpm-config rpm-build sed shadow-utils tar unzip util-linux which xz'

        config_opts['dist'] = 'rawhide'  # only useful for --resultdir variable subst
        config_opts['extra_chroot_dirs'] = [ '/run/lock', ]
        config_opts['releasever'] = '43'

        # https://fedoraproject.org/wiki/Changes/BuildWithDNF5
        config_opts['package_manager'] = 'dnf5'

        config_opts['bootstrap_image'] = 'registry.fedoraproject.org/fedora:rawhide'
        config_opts['bootstrap_image_ready'] = True

        config_opts['description'] = 'Fedora Rawhide'

        config_opts['redhat_subscription_required'] = True

        config_opts['dnf.conf'] = """
        [main]
        keepcache=1
        system_cachedir=/var/cache/dnf
        debuglevel=10
        reposdir=/dev/null
        logfile=/var/log/yum.log
        retries=20
        obsoletes=1
        gpgcheck=0
        assumeyes=1
        syslog_ident=mock
        syslog_device=
        install_weak_deps=0
        metadata_expire=0
        best=1
        module_platform_id=platform:f{{ releasever }}
        protected_packages=
        user_agent={{ user_agent }}

        # repos

        [rhel-primitives-dev]
        name=rhel-primitives-dev
        baseurl=https://mtls.internal.console.redhat.com/api/pulp-content/rhel-primitives-dev/x86_64/
        enabled=1
        sslverify=0
        gpgcheck=0
        sslclientcert=/etc/pki/entitlement/1234.pem
        sslclientkey=/etc/pki/entitlement/1234-key.pem

        [fedora]
        name=fedora
        metalink=https://mirrors.fedoraproject.org/metalink?repo=rawhide&arch=$basearch
        enabled=1
        cost=2000
        """
        EOF

        chmod 0400 ~/.ssh/id_rsa
        export SSH_HOST=$(cat /ssh/host)
        export HOMEDIR=$(cat /ssh/user-dir)
        export SSH_ARGS="-o StrictHostKeyChecking=no"
        remote_cmd() { ssh $SSH_ARGS "$SSH_HOST" "$@" ; }
        send() { rsync -rva "$1" "$SSH_HOST:$2" ; }
        receive() { rsync -rva "$SSH_HOST:$1" "$2" ; }

        if [ "$SSH_HOST" == "localhost" ] ; then
          echo "Running at local host is not supported"
          exit 1
        fi

        workdir=/var/workdir

        remote_cmd echo "Hello from the other side!"

        # Allow mockbuilder (group mock) to read sources, and write results
        remote_cmd mkdir "$HOMEDIR/results" "$HOMEDIR/source" "$HOMEDIR/config"
        remote_cmd podman unshare setfacl -m g:135:r-x -m default:g:135:r-x "$HOMEDIR/source"
        remote_cmd podman unshare setfacl -m g:135:rwx -m default:g:135:rwx "$HOMEDIR/results"
        remote_cmd podman unshare setfacl -m g:135:r-x -m default:g:135:r-x "$HOMEDIR/config"

        VOLUME_MOUNTS=(
          -v "$HOMEDIR/source:/source"
          -v "$HOMEDIR/results:/results"
          -v "$HOMEDIR/config:/config"
        )
        send "$workdir/source/" "$HOMEDIR/source"
        send "$workdir/config/mock.cfg" "$HOMEDIR/config/mock.cfg"
        if [ -d "/additional-secret" ]; then
          remote_cmd mkdir "$HOMEDIR/additional-secret"
          remote_cmd podman unshare setfacl -m g:135:r-x -m default:g:135:r-x "$HOMEDIR/additional-secret"
          send "/additional-secret/" "$HOMEDIR/additional-secret"
          VOLUME_MOUNTS+=(-v "$HOMEDIR/additional-secret:/etc/pki/entitlement:Z")
        fi

        mock_img=$(params.script-environment-image)
        # podman pull has --retry=3 as a default, nevertheless it works only for download of blobs,
        # if manifest download fails it will not be applied
        for i in {1..5} ; do
            remote_cmd podman pull "$mock_img" && break
            sleep_time=$((i ** 2))
            echo "Retrying in $sleep_time seconds."
            sleep $sleep_time
        done

        if test "$(params.specfile)" != "null" ; then
          specfile_name=$(params.specfile)
        else
          specfile_prefix=$(params.package-name)
          specfile_name="${specfile_prefix}.spec"
        fi
        ADDITIONAL_VOLUME_MOUNTS=()
        while [[ $# -gt 0 ]]; do
          case $1 in
          --additional-volume-mounts)
            shift
            while [[ $# -gt 0 && $1 != --* ]]; do
              ADDITIONAL_VOLUME_MOUNTS+=("$1")
              shift
            done
            ;;
          *)
            echo "unexpected argument: $1" >&2
            exit 2
            ;;
          esac
        done

        success=true
        VOLUME_MOUNTS=(
          -v "$HOMEDIR/source:/source"
          -v "$HOMEDIR/results:/results"
        )
        for mount in "${ADDITIONAL_VOLUME_MOUNTS[@]}"; do
          VOLUME_MOUNTS+=(-v "$mount")
        done

        remote_cmd podman run -u mockbuilder \
                              -e KOJI_TARGET="$(params.koji-target)" \
                              "${VOLUME_MOUNTS[@]}" \
                              --init --privileged --rm -ti "$mock_img" \
            mock -r /config/mock.cfg \
                --spec /source/$specfile_name \
                --sources /source --resultdir /results \
                --calculate-build-dependencies \
        || success=false

        # display dnf logs (no matter the mock exit status), and propagate the
        # mock failure (terminates the whole script)
        remote_cmd "tar xvfO '$HOMEDIR'/results/chroot_scan.tar.gz 2>&1 | cat"
        $success

        remote_cmd podman run -v "$HOMEDIR/results:/results" \
                              --privileged --rm -ti "$mock_img" \
            mock-hermetic-repo \
            --lockfile /results/buildroot_lock.json \
            --output-repo /results/buildroot_repo

        resultdir=$workdir/results/$arch/results
        mkdir -p "$resultdir"
        # Send only repo and lockfile, ignore other artifacts
        receive "$HOMEDIR/results/buildroot_lock.json" "$resultdir/buildroot_lock.json"
        receive "$HOMEDIR/results/buildroot_repo" "$resultdir"
        cat "$resultdir/buildroot_lock.json"
      volumeMounts:
        - mountPath: /ssh
          name: ssh
          readOnly: true
        - mountPath: /additional-secret
          name: additional-secret
      computeResources:
        requests:
          ephemeral-storage: 5Gi
      env:
      - name: ADDITIONAL_SECRET
        value: $(params.ADDITIONAL_SECRET)
    - name: create-trusted-artifact
      image: quay.io/redhat-appstudio/build-trusted-artifacts:latest@sha256:9b180776a41d9a22a1c51539f1647c60defbbd55b44bbebdd4130e33512d8b0d
      args:
        - create
        - --store
        - $(params.ociStorage)
        - $(results.calculation-artifact.path)=/var/workdir/results
  volumes:
    - name: ssh
      secret:
        optional: false
        secretName: multi-platform-ssh-$(context.taskRun.name)
    - name: workdir
      emptyDir: {}
    - name: additional-secret
      secret:
        optional: true
        secretName: $(params.ADDITIONAL_SECRET)
