---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  annotations:
    tekton.dev/tags: rpm-build
  name: generate-mock-config
spec:
  description: Generate Mock configuration template
  params:
    - description: Architecture to generate Mock configuration for
      name: arch
      type: string
    - description: RPM Build environment OCI image to run scripts in
      name: script-environment-image
      type: string
  results:
    - name: mock-config-file
      type: string
      description: Generated Mock configuration file (as a string)
  steps:
    - name: generate-mock-config
      image: $(params.script-environment-image)
      env:
        - name: arch
          value: $(params.arch)
      script: |
        #!/bin/bash
        set -ex
        set -o pipefail

        cat <<EOF > /tmp/mock.cfg
        config_opts['target_arch'] = '$arch'
        config_opts['legal_host_arches'] = ('$arch',)

        config_opts['root'] = 'local-{{ target_arch }}'

        # NOTE: The prefetched RPMs repo doesn't include this. Should it?
        # config_opts['chroot_setup_cmd'] = 'install @buildsys-build'
        # NOTE: The buildsys repo we got from hermeto doesn't have the buildsys-build group defined. So
        # we just expand the group into individual packages here.
        config_opts['chroot_setup_cmd'] = 'install bash bzip2 coreutils cpio diffutils fedora-release-common findutils gawk glibc-minimal-langpack grep gzip info patch redhat-rpm-config rpm-build sed shadow-utils tar unzip util-linux which xz'

        config_opts['dist'] = 'rawhide'  # only useful for --resultdir variable subst
        config_opts['extra_chroot_dirs'] = [ '/run/lock', ]
        config_opts['releasever'] = '43'

        # https://fedoraproject.org/wiki/Changes/BuildWithDNF5
        config_opts['package_manager'] = 'dnf5'

        config_opts['bootstrap_image'] = 'registry.fedoraproject.org/fedora:rawhide'
        config_opts['bootstrap_image_ready'] = True

        config_opts['description'] = 'Fedora Rawhide'

        config_opts['redhat_subscription_required'] = False

        config_opts['dnf.conf'] = """
        [main]
        keepcache=1
        system_cachedir=/var/cache/dnf
        debuglevel=10
        reposdir=/dev/null
        logfile=/var/log/yum.log
        retries=20
        obsoletes=1
        gpgcheck=0
        assumeyes=1
        syslog_ident=mock
        syslog_device=
        install_weak_deps=0
        metadata_expire=0
        best=1
        module_platform_id=platform:f{{ releasever }}
        protected_packages=
        user_agent={{ user_agent }}

        # repos

        [hummingbird]
        name=hummingbird
        baseurl=https://console.redhat.com/api/pulp-content/public-hummingbird/$arch/
        enabled=1
        sslverify=0
        gpgcheck=0
        sslcacert=/etc/pki/tls/certs/ca-bundle.crt
        priority=10

        [fedora]
        name=fedora
        metalink=https://mirrors.fedoraproject.org/metalink?repo=rawhide&arch=\$basearch
        enabled=1
        priority=100
        cost=2000
        """
        EOF

        cat /tmp/mock.cfg | tee "$(results.mock-config-file.path)"
